#!/usr/bin/env bash
# Displays "To infinity and beyond" and "I am invicible" when receiving a SIGTERM

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
